// <auto-generated />
using System;
using GestaoProjeto.Infra.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestaoProjeto.Infra.Database.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestaoProjeto.Infra.Domain.Departamentos.Departamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Departamento", (string)null);
                });

            modelBuilder.Entity("GestaoProjeto.Infra.Domain.Funcionarios.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Funcionario", (string)null);
                });

            modelBuilder.Entity("GestaoProjeto.Infra.Domain.Participacoes.Participacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartamentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("DepartamentoId", "FuncionarioId", "ProjetoId")
                        .IsUnique()
                        .HasDatabaseName("IDX_DepartamentoId_FuncionarioId_ProjetoId");

                    b.ToTable("Participacao", (string)null);
                });

            modelBuilder.Entity("GestaoProjeto.Infra.Domain.Projetos.Projeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartamentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Projeto", (string)null);
                });

            modelBuilder.Entity("GestaoProjeto.Infra.Domain.Funcionarios.Funcionario", b =>
                {
                    b.HasOne("GestaoProjeto.Infra.Domain.Funcionarios.Funcionario", "Supervisor")
                        .WithMany("Funcionarios")
                        .HasForeignKey("SupervisorId");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("GestaoProjeto.Infra.Domain.Participacoes.Participacao", b =>
                {
                    b.HasOne("GestaoProjeto.Infra.Domain.Departamentos.Departamento", "Departamento")
                        .WithMany("Participacoes")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoProjeto.Infra.Domain.Funcionarios.Funcionario", "Funcionario")
                        .WithMany("Participacoes")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoProjeto.Infra.Domain.Projetos.Projeto", "Projeto")
                        .WithMany("Participacoes")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Funcionario");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("GestaoProjeto.Infra.Domain.Projetos.Projeto", b =>
                {
                    b.HasOne("GestaoProjeto.Infra.Domain.Departamentos.Departamento", "Departamento")
                        .WithMany("Projetos")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("GestaoProjeto.Infra.Domain.Departamentos.Departamento", b =>
                {
                    b.Navigation("Participacoes");

                    b.Navigation("Projetos");
                });

            modelBuilder.Entity("GestaoProjeto.Infra.Domain.Funcionarios.Funcionario", b =>
                {
                    b.Navigation("Funcionarios");

                    b.Navigation("Participacoes");
                });

            modelBuilder.Entity("GestaoProjeto.Infra.Domain.Projetos.Projeto", b =>
                {
                    b.Navigation("Participacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
